TST_EXE := tst
CCFLAGS := -c
OBJ_FILES := assets.o model.o raster.o render.o font.o events.o clear_qk.o tst_env.o

$(TST_EXE): $(OBJ_FILES)
	cc68x $(OBJ_FILES) -o tst

tst_env.o: tst_env.c
	cc68x $(CCFLAGS) $<

assets.o: assets.c assets.h
	cc68x $(CCFLAGS) $<

model.o: model.c model.h
	cc68x $(CCFLAGS) $<

raster.o: raster.c raster.h
	cc68x $(CCFLAGS) $<

render.o: render.c render.h
	cc68x $(CCFLAGS) $<

font.o: font.c font.h
	cc68x $(CCFLAGS) $<

events.o: events.c events.h
	cc68x $(CCFLAGS) $<

clear_qk.o: clear_qk.s
	gen -D -L2 $<
