TST_EXE := tst
CCFLAGS := -c
OBJ_FILES := assets.o model.o raster.o render.o font.o events.o tetris.o

$(TST_EXE): $(OBJ_FILES)
	cc68x $(OBJ_FILES) -o tst

tetris.o: tetris.c
	cc68x $(CCFLAGS) $<

assets.o: assets.c assets.h
	cc68x $(CCFLAGS) $<

model.o: model.c model.h
	cc68x $(CCFLAGS) $<

raster.o: raster.c raster.h
	cc68x $(CCFLAGS) $<

render.o: render.c render.h
	cc68x $(CCFLAGS) $<

font.o: font.c font.h
	cc68x $(CCFLAGS) $<

events.o: events.c events.h
	cc68x $(CCFLAGS) $<
